"""Keep Yomine-generated dictionaries out of reference evidence and analysis."""
import hashlib
import json
from pathlib import Path

EXCLUSION_REASON = "Anilist Top 500 is generated by Yomine and is not independent evidence."


def include_source(name):
    return name.strip().lower() != "anilist top 500"


def prepare_frequencies(db):
    # A TEMP view also protects consumers of legacy databases without modifying them.
    db.execute("""CREATE TEMP VIEW IF NOT EXISTS research_frequencies AS
        SELECT * FROM main.frequencies
        WHERE lower(trim(dictionary)) != 'anilist top 500'""")


def source_manifest(db):
    manifest = json.loads(db.execute("SELECT value FROM metadata WHERE key='manifest'").fetchone()[0])
    manifest["frequency_sources"] = [s for s in manifest.get("frequency_sources", [])
                                     if include_source(s["dictionary"])]
    manifest.update(policy_manifest())
    return manifest


def policy_manifest():
    return {"excluded_frequency_sources": {"Anilist Top 500": EXCLUSION_REASON},
            "source_policy_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest()}
