name: Generate Changelog

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to generate changelog for'
        required: true
        type: string

jobs:
  changelog:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for changelog generation
    
    - name: Generate Changelog
      id: changelog
      uses: mikepenz/release-changelog-builder-action@v4
      with:
        configuration: ".github/changelog-config.json"
        toTag: ${{ github.event.release.tag_name || inputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Update Release with Changelog
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        body: ${{ steps.changelog.outputs.changelog }}
        append_body: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Print Changelog (manual run)
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "## Generated Changelog"
        echo "${{ steps.changelog.outputs.changelog }}"
